In [2]:
import numpy as np
import pickle
import os
import sys
from mindreadingautobots.sequence_generators import data_io

In [106]:
def generate_multitask_sparse_majority(n_tasks, n_bits, k, n_data, p_bitflip=0.0, seed=None):
    """
    Generate a multitask sparse majority dataset.
    
    Args:
        n_tasks: Number of subtasks (distinct versions of sparse majority)
        n_bits: Total length of task bits
        k: Size of the fixed subset for each majority calculation
        n_data: Number of data points to generate
        p_bitflip: Probability of flipping bits in the task bits (not control bits)
        seed: Random seed for reproducibility
        
    Returns:
        X: Array of shape (n_data, n_tasks + n_bits + 1) containing noiseless data:
           - First n_tasks bits are control bits (one-hot encoding of task)
           - Next n_bits are task bits
           - Last bit is the output (majority of relevant task bits)
        Z: Array of same shape as X but with noise in the task bits (if p_bitflip > 0)
        task_subsets: List of k indices for each task indicating which bits to use for majority
    """
    if seed is not None:
        np.random.seed(seed)
    
    # Initialize the dataset
    total_bits = n_tasks + n_bits + 1  # control bits + task bits + output bit
    X = np.zeros((n_data, total_bits), dtype=np.int32)
    
    # Generate random task subsets (each task uses a different subset of k indices)
    task_subsets = []
    for i in range(n_tasks):
        # Generate a random subset of k indices from the task bits
        subset = np.sort(np.random.choice(n_bits, k, replace=False))
        task_subsets.append(subset)
    
    # Generate data for each example
    for i in range(n_data):
        # Randomly select a task (which control bit to activate)
        active_task = np.random.randint(0, n_tasks)
        
        # Set the control bit (one-hot encoding)
        X[i, active_task] = 1
        
        # Generate random task bits
        task_bits = np.random.randint(0, 2, n_bits)
        X[i, n_tasks:n_tasks+n_bits] = task_bits
        
        # Compute the majority of the subset corresponding to the active task
        relevant_subset = task_subsets[active_task]
        relevant_bits = task_bits[relevant_subset]
        # If sum >= k/2, majority is 1, otherwise 0
        # For ties (sum = k/2), output 1 as specified
        majority = 1 if np.sum(relevant_bits) >= k/2 else 0
        
        # Set the output bit
        X[i, -1] = majority
    
    # Apply noise to task bits if specified
    if p_bitflip > 0:
        # Create a copy of X
        Z = np.copy(X)
        
        # Generate noise mask for task bits only
        flips = np.random.binomial(1, p_bitflip, size=(n_data, n_bits))
        
        # Apply noise to task bits only
        Z[:, n_tasks:n_tasks+n_bits] = np.logical_xor(
            X[:, n_tasks:n_tasks+n_bits], 
            flips
        ).astype(np.int32)
        
        # Keep the original output bit from X to test noise robustness
        # (not recomputing based on noisy bits)
        Z[:, -1] = X[:, -1]

        print(X, Z, task_subsets)            
        return X, Z, task_subsets

    else:
        return X, X, task_subsets

In [35]:
def verify_examples(X, task_subsets, n_tasks, num_examples=5):
    """Verify correctness of several examples in the dataset"""
    for i in range(min(num_examples, len(X))):
        example = X[i]
        
        # Determine which task is active
        active_task = np.argmax(example[:n_tasks])
        
        # Get the task bits
        task_bits = example[n_tasks:-1]
        
        # Get the subset for the active task
        relevant_subset = task_subsets[active_task]
        relevant_bits = task_bits[relevant_subset]
        
        # Compute expected parity
        expected_parity = np.sum(relevant_bits) % 2
        actual_parity = example[-1]
        
        print(f"Data: {X}")
        # Display the example
        print(f"\nExample {i+1}:")
        print(f"Full string: {''.join([str(x) for x in example[:-1]])}")
        print(f"Control bits: {''.join([str(x) for x in example[:n_tasks]])}")
        print(f"Task bits: {''.join(
            [str(x) for x in task_bits])}")
        print(f"Active task: {active_task+1}")
        print(f"Relevant subset indices: {relevant_subset}")
        print(f"Relevant bits: {relevant_bits}")
        print(f"Expected answer: {expected_parity}")
        print(f"Actual answer: {actual_parity}")
        print(f"Correct: {expected_parity == actual_parity}")

SyntaxError: unterminated string literal (detected at line 25) (2332664692.py, line 25)

In [108]:
# sys.path.append("../src")

n_tasks = 4  # Number of tasks
task_bits_length = 20  # Length of the task bits portion
k = 3  # Size of subset for parity calculation
n_train = 2000  # Number of training examples
n_val = 10000  # Number of validation examples
p_bitflips = [0.05, 0.1, 0.2, 0.3]  # Array of bit flip probabilities
seed = 1234  # Random seed

for p_bitflip in p_bitflips:
    # Generate the dataset
    print(f"\nGenerating multitask_sparse_parity with {n_tasks} tasks, {task_bits_length} task bits, k={k}, noise={p_bitflip}")
    X, Z, task_subsets = generate_multitask_sparse_majority(
        n_tasks=n_tasks,
        n_bits=task_bits_length,
        k=k,
        n_data=n_train + n_val,
        p_bitflip=p_bitflip,
        seed=seed
    )

    # Print the task subsets (which bits are used for each task)
    for i, subset in enumerate(task_subsets):
        print(f"Task {i+1} uses bits {subset} for parity calculation")
    print(task_subsets)
    # Split into train and validation sets
    X_train = X[:n_train]
    X_val = X[n_train:]
    Z_train = Z[:n_train]
    Z_val = Z[n_train:]

    # Verify some examples
    # print("\nVerifying noiseless training examples:")
    # verify_examples(X_train, task_subsets, n_tasks, 2)

    # if p_bitflip > 0:
    #     print("\nVerifying noisy training examples:")
    #     verify_examples(Z_train, task_subsets, n_tasks, 2)

    # Compare original and noisy examples
    if p_bitflip > 0:
        print("\nComparing original and noisy examples:")
        for i in range(2):  # Show 2 examples
            print(f"Example {i+1}:")
            print(f"Original task bits: {X_train[i, n_tasks:-1]}")
            print(f"Noisy task bits: {Z_train[i, n_tasks:-1]}")
            print(f"Bits flipped: {np.sum(X_train[i, n_tasks:-1] != Z_train[i, n_tasks:-1])}")
            print(f"Original answer: {X_train[i, -1]}")
            print(f"Noisy answer: {Z_train[i, -1]}\n")

    # Create directory for this bit flip rate
    bf_str = '0' if p_bitflip == 0 else str(int(p_bitflip * 100))
    output_dir = f'./multitask_sparse_majority_ntasks{task_bits_length}_ncontrol{n_tasks}_k{k}_ndata{n_train}_bf{bf_str}_seed{seed}'
    os.makedirs(output_dir, exist_ok=True)

    # Save the datasets
    data_io.save_numpy_as_dict(X_train, f'{output_dir}/noiseless_train.pkl')
    data_io.save_numpy_as_dict(X_val, f'{output_dir}/noiseless_val.pkl')
    
    # For zero bit flip, save noiseless data as train.pkl and val.pkl as well
    if p_bitflip == 0:
        data_io.save_numpy_as_dict(X_train, f'{output_dir}/train.pkl')
        data_io.save_numpy_as_dict(X_val, f'{output_dir}/val.pkl')
    else:
        data_io.save_numpy_as_dict(Z_train, f'{output_dir}/train.pkl')
        data_io.save_numpy_as_dict(Z_val, f'{output_dir}/val.pkl')
    
    # Save task subsets
    with open(f'{output_dir}/task_subsets.pkl', 'wb') as f:
        pickle.dump(task_subsets, f)

    # Print saved data
    print("\nPrinting saved data:")
    for filename in ['noiseless_train.pkl', 'noiseless_val.pkl', 'train.pkl', 'val.pkl']:
        filepath = f'{output_dir}/{filename}'
        if os.path.exists(filepath):
            with open(filepath, 'rb') as f:
                data = pickle.load(f)
                print(f"\nContents of {filename}:")
                print(f"Number of examples: {len(data['line'])}")
                print("First example:")
                print(f"Line: {data['line'][0]}")
                print(f"Label: {data['label'][0]}")


Generating multitask_sparse_parity with 4 tasks, 20 task bits, k=3, noise=0.05
[[0 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 1]
 [1 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 0 1]
 [1 0 0 ... 0 1 0]] [[0 0 0 ... 0 1 0]
 [1 0 0 ... 0 1 1]
 [1 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 1 1 0]
 [0 0 0 ... 1 0 1]
 [1 0 0 ... 0 1 0]] [array([ 2,  3, 13]), array([ 8, 13, 19]), array([ 2,  3, 17]), array([ 0,  7, 18])]
Task 1 uses bits [ 2  3 13] for parity calculation
Task 2 uses bits [ 8 13 19] for parity calculation
Task 3 uses bits [ 2  3 17] for parity calculation
Task 4 uses bits [ 0  7 18] for parity calculation
[array([ 2,  3, 13]), array([ 8, 13, 19]), array([ 2,  3, 17]), array([ 0,  7, 18])]

Comparing original and noisy examples:
Example 1:
Original task bits: [0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0 1]
Noisy task bits: [0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1]
Bits flipped: 1
Original answer: 0
Noisy answer: 0

Example 2:
Original task bits: [1 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1]
Noisy tas

In [110]:
folder_path = "multitask_sparse_majority_ntasks20_ncontrol4_k3_ndata2000_bf5_seed1234"
noisy_data_path = folder_path + "/val.pkl"
noiseless_data_path = folder_path + "/noiseless_val.pkl"
task_path = folder_path + "/task_subsets.pkl"

with open(noisy_data_path, 'rb') as f:
    noisy_data = pickle.load(f)
with open(noiseless_data_path, 'rb') as f:
    noiseless_data = pickle.load(f)
with open(task_path, 'rb') as f:
    task_subsets = pickle.load(f)
  
labels = noisy_data['label']
data = noisy_data['line']



  
encoding_map = {
    '0001': task_subsets[3],
    '0010': task_subsets[2],
    '0100': task_subsets[1],
    '1000': task_subsets[0]
}


for i in range(len(data)):
  one_hot_encoding = (data[i][:4])
  relevant_indices = encoding_map[one_hot_encoding]
  
  task_bits = data[i][4:] 
  relevant_bits = [int(task_bits[i]) for i in relevant_indices]  

  majority = sum(relevant_bits) >= 2 

  label = int(labels[i])

  assert majority == label

  
  
  









AssertionError: 

20